version: '3.8'

services:
  postgres-db:
    image: postgres:16
    container_name: erp_database
    environment:
      POSTGRES_USER: admin_erp
      POSTGRES_PASSWORD: kalonz
      POSTGRES_DB: erpdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: